language: php

php:
  - 5.5
  - 5.6
  - 7
  - 7.1

addons:
  apt:
    packages:
      - parallel

sudo: false
cache:
  directories:
    - $HOME/.composer/cache

notifications:
  email:
    - typo3@helhum.io

before_install:
  - if php -i | grep -q xdebug; then phpenv config-rm xdebug.ini; fi
  - composer self-update
  - composer --version

before_script:
  - composer install

script:
  - >
    echo;
    echo "Running unit tests";
    vendor/bin/phpunit tests/Unit/
  - >
    echo;
    echo "Running php lint";
    find . -name \*.php ! -path "./vendor/*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;
